
version: '2.1'
services:
  base-nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      #- IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR}
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
    cap_add: # ignored in swarm mode (docker-compose yaml version 3.x)
    - NET_BIND_SERVICE
    command: ["sudo", "nginx", "-g", "daemon off;"]
    image: cirepo/nginx-proxy:1.15.0-alpine
    restart: always
