
version: '2.1'
services:
  nginx-proxy-develop:
    extends:
      file: docker-compose-base.yml
      service: base-nginx-proxy
    container_name: ${CONTAINER_HOST_NAME:-standalone.nginx-proxy}
    hostname: ${CONTAINER_HOST_NAME:-standalone.nginx-proxy}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.nginx-proxy}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/nginx-proxy/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.32}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::32}
    ports:
    - "${NEXUS3_DOCKER_HOSTED_PORT:-5010}:${NEXUS3_DOCKER_HOSTED_PORT:-5010}/tcp"
    - "${NEXUS3_DOCKER_PUBLIC_PORT:-5000}:${NEXUS3_DOCKER_PUBLIC_PORT:-5000}/tcp"
    - "${NONSECUREPORT_EXPOSED:-80}:${NONSECUREPORT:-1080}/tcp"

    environment:
      NONSECUREPORT: ${NONSECUREPORT:-1080}
      NONSECUREPORT_EXPOSED: ${NONSECUREPORT_EXPOSED:-80}



      # hostname not works if bound it in /etc/hosts
      NGINX_PROXY_CONFIG: |-
        [



          {"host": "172.16.238.31", "port": ${NEXUS3_DOCKER_PUBLIC_PORT:-5000}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
            "server_location": "/", "server_name": "docker-mirror${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NEXUS3_DOCKER_PUBLIC_PORT:-5000}, "server_protocol": "http"},




          {"host": "172.16.238.31", "port": ${NEXUS3_DOCKER_HOSTED_PORT:-5010}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
            "server_location": "/", "server_name": "docker-registry${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NEXUS3_DOCKER_HOSTED_PORT:-5010}, "server_protocol": "http"},





          {"host": "172.16.238.31", "port": ${NEXUS3_PORT:-28081}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
            "server_location": "~ ^/(.*)", "server_name": "fileserver${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http",
            "server_proxy_pass_context": "/nexus/repository/files/$$1"},

          {"host": "172.16.238.21", "port": ${GIT_HTTP_PORT:-10080}, "protocol": "http", "anonymous": "false",
            "server_location": "/", "server_name": "git${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http"},

          {"host": "172.16.238.31", "port": ${NEXUS3_PORT:-28081}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
            "server_location": "~ ^/(.*)", "server_name": "maven-site${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http",
            "server_proxy_pass_context": "/nexus/repository/mvnsite/$$1"},

          {"host": "172.16.238.31", "port": ${NEXUS3_PORT:-28081}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
            "server_location": "/", "server_name": "nexus3${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http"},

          {"host": "172.16.238.31", "port": ${NEXUS3_PORT:-28081}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
              "server_location": "/", "server_name": "node${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http"},

          {"host": "172.16.238.31", "port": ${NEXUS3_PORT:-28081}, "protocol": "http", "anonymous": "read", "pass": "${BASIC_AUTH_PASS:-deployment}", "user": "${BASIC_AUTH_USER:-deployment}",
              "server_location": "/", "server_name": "npm${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http"},

          {"host": "172.16.238.67", "port": ${SONARQUBE_EXTERNAL_PORT:-9000}, "protocol": "http", "anonymous": "false",
              "server_location": "/", "server_name": "sonar${DOT_INSTANCE_DOMAIN:-}", "server_port": ${NONSECUREPORT:-1080}, "server_protocol": "http"}
        ]

    volumes:
    - cache:/var/cache/nginx
    - ${NGINX_CERTS:-certs}:/etc/letsencrypt
      # Files under archive is not visible if mount data/certs only. This might be a bug of Docker for Mac 2.0.0.3
    - ${NGINX_CERTS:-certs-archive}:/etc/letsencrypt/archive
    - conf.d:/etc/nginx/conf.d
    - log:/var/log/letsencrypt
    - log:/var/log/nginx

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  cache:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/cache
      o: bind
  certs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/certs
      o: bind
  # Files under archive is not visible if mount data/certs only. This might be a bug of Docker for Mac 2.0.0.3
  certs-archive:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/certs/archive
      o: bind
  conf.d:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/conf.d
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
