
version: '2.1'
services:
  base-nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      #- IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR}
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_IMAGE_TAG=${IMAGE_ARG_IMAGE_TAG:-1.15.0-alpine}
    cap_add: # ignored in swarm mode (docker-compose yaml version 3.x)
    - NET_BIND_SERVICE
    command: ["sudo", "nginx", "-g", "daemon off;"]
    environment:
    - OVERWRITE_EXISTING_CONF=${OVERWRITE_EXISTING_CONF:-true}
    - SKIP_CONF_GENERATION=${SKIP_CONF_GENERATION:-false}
    image: ${IMAGE_PREFIX:-cirepo}/${IMAGE_NAME:-nginx-proxy}:${IMAGE_TAG:-1.15.0-alpine}
    restart: always
